### ISSUE TITLE
Boolean arguments do not always need explicit values.

### ISSUE THREAD

**Issue by cznic** [alexflint/go-arg#1]
From [README.md](https://github.com/alexflint/go-arg/blob/60f2612c0c59b979f71241405515e722bf6943f0/README.md#rationale):
> Boolean arguments must have explicit values, so ./prog -debug=1 sets debug to true but ./myprog -debug does not.

Not true. If you define

```go
debug := flag.Bool("debug", false, "whatever")
```

Then passing `-debug` is enough to have the variable `debug` hold a `true` value.

**Comment by alexflint** [comment]
Thanks for the catch - fixed.
