### ISSUE TITLE
Issue in Struct Parsing with Duplicate Property Names in Substructs

### ISSUE THREAD

**Issue by ShadowStrikerJ** [alexflint/go-arg#100]
There appears to be an issue when it parses structs in the normal way, for example:
```
type Config struct {
	Environment string `arg:"env:GO_ENV"`
	ServerConfig
         DBConfig
 }

type ServerConfig struct {
	Host    string `arg:"env:SERVER_HOST"`
	Port    string `arg:"env:SERVER_PORT"`
	Version string `arg:"env:SERVER_VERSION"`
}
type DBConfig struct {
	Host    string `arg:"env:DB_HOST"`
}
```

In this instance it returns back an error: 

> `panic: reflect: call of reflect.Value.Type on zero Value` 

From doing some testing it appears to be when two of the nested structs have one of the same property names

**Comment by alexflint** [comment]
Thank you for identifying this @ShadowStrikerJ. I've added a test for this case and the issue is fixed in #107.
