### ISSUE TITLE
Subcommands don't display parent command arguments

### ISSUE THREAD

**Issue by dallbee** [alexflint/go-arg#101]
Currently, subcommands inherit the arguments of their parent. That's great, but the help for those subcommands doesn't display the inherited arguments. From a UX standpoint, that's misleading - it  looks like that those arguments aren't allowed on the subcommand.

Was this the intended behavior? I'd be happy to open a PR if not.

**Comment by alexflint** [comment]
Ah no this is not the intended behavior. A pr would be welcome.

**Comment by dallbee** [comment]
Was easy enough to do, the code is well structured!

My current output looks like this:
```.sh
dylan@iron ~/P/g/ex> go run main.go sub --help
Usage: main sub [--enable] THREADS

Positional arguments:
  THREADS

Options:
  --enable

Global Options:
  --verbose
  --help, -h             display this help and exit
```

Where the "Global Options" category is displayed only if you're on the help for a subcommand.

Would you prefer that, or more of a merged approach?

```.sh
dylan@iron ~/P/g/ex> go run main.go sub --help
Usage: main sub [--enable] THREADS

Positional arguments:
  THREADS

Options:
  --enable
  --verbose
  --help, -h             display this help and exit
```

**Comment by alexflint** [comment]
I think "Global options" is a good a and clear choice.

Does your code handle the case of nested subcommands? So if I write a program that gets invoked as `./program cmd subcmd subsubcmd --help` then under "Global options" should be listed all the options from `./program`, `./program cmd`, and `./program cmd subcmd`.

**Comment by dallbee** [comment]
Thanks for the feedback. I'll put the PR up tonight when I'm back at a computer.

> Does your code handle the case of nested subcommands? 

Yeah it works exactly as you describe.
