### ISSUE TITLE
Support for version flag (built in support)

### ISSUE THREAD

**Issue by walle** [alexflint/go-arg#11]
I would like to add another flag the parser is aware of besides `--help`, and that is `--version`. This is to enable a simple interface for outputting the version information, which is pretty standard. Instead of every application reimplementing this and "obfuscating" their main functions this should be in the library. In my opinion.

If you thing this is a good idea I could submit a pull request with this functionality, with tests and documentation of course.

My idea is to add `arg.SetVersion(version string)` that should be optionally called before `arg.MustParse`.
Then parse the `--version` flag together with the help flag at https://github.com/alexflint/go-arg/blob/master/parse.go#L179
If it's not called no `--version` flag exists for the application.

What do you think of this idea?

**Comment by alexflint** [comment]
Yeah I agree there should be builtin support for a version flag. I like the idea of a global `arg.SetVersion` function. I think there should also be a corresponding `SetVersion` on the `Parser` type, and the global `arg.SetVersion` should delegate to this using a global `var defaultParser *Parser` at the module level.
