### ISSUE TITLE
--foo=bar as positional

### ISSUE THREAD

**Issue by Pirionfr** [alexflint/go-arg#117]
I have a launcher that take multi defined arg and 2 positional arg
the first positional arg is the name of the program and the second his parameters
the program can take parameter like --foo=bar
but i get error : "error: unknown argument --foo=bar"

example : 
```
import (
	"os"
	"strings"
	
	"github.com/alexflint/go-arg"
)

func main() {
	var args struct {
		Name        string   `arg:"positional"`
		Parameters   []string `arg:"positional"`
	}
	
	os.Args = strings.Split("./launcher program --foo=bar", " ")
	arg.MustParse(&args)
}
```
https://play.golang.org/p/xzvCZhjL0Pn

there is a way to having --foo=bar in positional Arguments ?

**Comment by alexflint** [comment]
Ah in this case you must invoke your program with

./launch -- program --foo=bar

Does that work for you?

**Comment by Pirionfr** [comment]
yes thanks.
