### ISSUE TITLE
GetDescription doesn't work for sub commands

### ISSUE THREAD

**Issue by gpie3k** [alexflint/go-arg#118]
GetDescription for sub commands is not used for writing help text

**Comment by alexflint** [comment]
You should use just "Description", not "GetDescription":

```
type subcmd struct {
   // ... options here
}

func (s *subcmd) Description() string {
  return "Does such-and-such"
}
```

Feel free to re-open if this doesn't work for you.

**Comment by gpie3k** [comment]
Doesn't work. I cannot reopen this issue. I will create new one...
