### ISSUE TITLE
Embedded structs doesn't work for sub commands

### ISSUE THREAD

**Issue by gpie3k** [alexflint/go-arg#119]
after adding embedded structure to sub command I go:
ArgsAddJob.Test: *job.ArgsTests fields are not supported

```
type ArgsTests struct {
	val1 string
	val2 string
}

type ArgsAddJob struct {
	Test          *ArgsTests
}
```

where ArgsAddJob is subcommand

**Comment by alexflint** [comment]
So you have a few options here. If you want the fields in "test" to show up directly as options underneath "ArgsAddJob", then you need to (1) export val1 and val2 by renaming to "Val1" and "Val2", and (2) directly embed the struct like this: 

```go
type ArgsTests struct {
	Val1 string
	Val2 string
}

type ArgsAddJob struct {
	ArgsTests
}
```

Alternatively, if you want "ArgsTest" to be a subcommand of "ArgsAddJob" then you still need to name val1 to Val1 and val2 to Val2, and then you can do this:

```go
type ArgsTests struct {
	Val1 string
	Val2 string
}

type ArgsAddJob struct {
	Test *ArgsTests `arg:"subcommand"`
}
```
 
A third option is that you might want to keep the "Test" field but have go-arg ignore it completely (I'm guessing this is not what you want but just in case I'm including this example):


```go
type ArgsTests struct {
	val1 string
	val2 string
}

type ArgsAddJob struct {
	Test *ArgsTests `arg:"-"`
}
```
 
I hope this helps - feel free to re-open if this still doesn't work for you.
