### ISSUE TITLE
Can you explicitly specify both short and long argument names?

### ISSUE THREAD

**Issue by atc0005** [alexflint/go-arg#121]
In the docs it appears that I can explictly specify either the short flag name or the long flag name, but not both. To borrow the example from https://pkg.go.dev/github.com/alexflint/go-arg?tab=doc:

```golang
var args struct {
	Input string   `arg:"positional"`
	Log string     `arg:"positional,required"`
	Debug bool     `arg:"-d" help:"turn on debug mode"`
	RealMode bool  `arg:"--real"
	Wr io.Writer   `arg:"-"`
}
```

This does not appear to be supported, correct?

```golang
var args struct {
        // ...
	Debug bool     `arg:"-d, --debug-mode" help:"turn on debug mode"`
        // ...
}
```

I have a project currently using the `flag` standard library package where I've specified short and long form flags which do not match the struct field name. I'd like to use the same short and long form flag names with this package if possible, but I understand if that's not supported.

Snippet for reference:

```golang

func (c *Config) handleFlagsConfig() {

// ...
	flag.StringVar(&c.configFile, "cf", "", configFileFlagHelp+" (shorthand)")
	flag.StringVar(&c.configFile, "config-file", "", configFileFlagHelp)
// ...

```

Thanks for your help.

**Comment by alexflint** [comment]
Hey @atc0005, it ought to be possible to specify both a short and a long name, and it should work using the code you provided here. Does that not work? If it doesn't work, I should fix that. If it does work, I should probably add documentation and examples that make it clear that one can do this.

**Comment by atc0005** [comment]
I don't think I tried it, I just went off what I saw in the docs and what I thought I saw in the code. Since I don't have a lot of experience (in general and with reflection), it is likely that I misunderstood what I was looking at.

I will give this a try in the morning and report back.

**Comment by atc0005** [comment]
I added a short flag to an existing config struct; the short flag was picked up and shown as a valid option alongside the long flag name in the help output and worked as expected from the command-line. This is great.

> If it does work, I should probably add documentation and examples that make it clear that one can do this.

This sounds useful, thank you. 

Suggestions (I don't presume to say that these ideas are any better that what you might already have in mind):

![image](https://user-images.githubusercontent.com/36716992/89122568-b88dcf00-d48d-11ea-8f55-172ae94d0e2f.png)

Insert some wording there to indicate that both forms are supported for the same field.

Tangent:

Most (all?) of the existing short form flag examples are also 1 character in length. I imagine that this is either a standard or is so common it might as well be, but it might be useful to also give an example of a short-form flag that is 2-3 characters in length.

Unless 1 char short-form flags are the standard, maybe add another field to the `args` struct and use a short-form flag that is longer than 1 character.

I can submit a PR if this sounds useful.
