### ISSUE TITLE
Positional argument before positional,required argument doesn't work

### ISSUE THREAD

**Issue by Keithcat1** [alexflint/go-arg#124]
I have the following code:
```
package main
import(
	"github.com/alexflint/go-arg"
)
type args struct {
	Name string `arg:"positional"`
	Age int `arg:"positional,required"`
}

func main() {
	a:=args{}
	arg.MustParse(&a)
}
```
This is a weird example, but it shows what I'd like to do.
When I run "./cli 15", I want it to leave name alone and set age to 15, but it seems to assume that I passed in the value for name, because I get this:
Usage: cli NAME AGE
error: age is required

**Comment by atc0005** [comment]
Try this:

```golang
// ...
type args struct {
        Age int `arg:"positional,required"`
        Name string `arg:"positional"`
}
// ...
```

**Comment by Keithcat1** [comment]
Sorry, I should be more clear on what I want to have happend:
When I run "./cli 15", I want it to set age to 15 and leave name alone, and when I run "./cli "Me" 15" I want it to set Name to "Me" and Age to 15.
Now that I think about it, I could maybe do this with a []string slice, but that's kind of clunky.

**Comment by atc0005** [comment]
> When I run "./cli 15", I want it to set age to 15 and leave name alone, and when I run "./cli "Me" 15" I want it to set Name to "Me" and Age to 15.

Ah, I've not used this package for that specific use case, so unfortunately I have no advice there.

**Comment by alexflint** [comment]
You would have to do something like this:
```go
var args struct {
  First *string `arg:"positional,required"
  Second *string `arg:"positional"`
}
arg.MustParse(&args)
var name string
var age int
if args.Second == nil {
  age = strconv.Atoi(*args.First)
} else {
  name = *args.First
  age = strconv.Atoi(*args.Second)
}
```

**Comment by alexflint** [comment]
Closing for now but feel free to reopen if you have further questions.
