### ISSUE TITLE
Automatically set the short name of a field to its first letter

### ISSUE THREAD

**Issue by Keithcat1** [alexflint/go-arg#125]
It would be nice if go-arg automatically set a fields short name to its first letter.
Most command line apps let you specify flags this way. I know that I can do this manually, but it seems pointless if this could be made the default.
You could always add an option to turn this feature off if you don't want to use it.

**Comment by alexflint** [comment]
But what to do when there are two options with the same first letter? For example:

```go
var args struct {
  Cat string
  Car string
}
```

Should these both be associated with `-c`?

**Comment by alexflint** [comment]
Closing this for now, feel free to re-open if you'd like to discuss further.
