### ISSUE TITLE
Passing multiple values via CLI parameter doesn't work

### ISSUE THREAD

**Issue by JonasPf** [alexflint/go-arg#127]
Consider the following code:

```
package main

import (
	"fmt"

	"github.com/alexflint/go-arg"
)

var args struct {
	Test []string `arg:"env:TEST,--test,required"`
}

func main() {
	arg.MustParse(&args)
	fmt.Printf("%+v\n", args.Test)
}
```

If I pass multiple values by environment variable it works as expected:

```
$ TEST="foo,bar" go run main.go
[foo bar]
```

However if I try to use the cli parameter to do the same it doesn't split on the comma:

```
$ go run main.go --test="foo,bar"
[foo,bar]
```

Some cli tools allow for the same parameter key to be used multiple times to specify multiple values, that doesn't work either:

```
$ go run main.go --test="foo" --test="bar"
[bar]
```

**Comment by alexflint** [comment]
Hey @JonasPf you can do this:
```
go run main.go --test foo bar
```

**Comment by JonasPf** [comment]
That's great, thanks for the tip!
