### ISSUE TITLE
Optional long name

### ISSUE THREAD

**Issue by Andrew-Morozko** [alexflint/go-arg#130]
Hello Alex!

I want to make the long name optional, what do you think about that? Defining them could look something like this `--` without a name seems pretty clear.
```go
type Args struct {
	EnvOnly   string `arg:"--,env"`
	ShortOnly string `arg:"--,-s"`
}
```

Help could look like this, (perhaps add hinting at the env-only arguments)
```
Optional long name example
Usage: example [-s SHORTONLY]

Options:
  -s SHORTONLY
  --help, -h             display this help and exit
```

Can create a pull request if you're OK with this.

**Comment by alexflint** [comment]
Oh great, yes, I think this would be good.
