### ISSUE TITLE
Find a way to print help message for nested subcommands

### ISSUE THREAD

**Issue by Keithcat1** [alexflint/go-arg#134]
I have an app like this:
app
    pack
        build
        extract
        generate
If I run "app pack", nothing happens. I have to run "app pack --help" to get something useful, which is probably not emediately obvious.

**Comment by alexflint** [comment]
Hey @Keithcat1, do you mean when you run `$ app pack` you're expecting that the help message for the `pack` subcommand would be printed? I don't think we want that to be the default behavior for all applications using this library but you could get this behavior by using a required argument like this:

```go
type packArgs struct {
  Something string `arg:"required"`
}

var args struct {
   Pack *packArgs `arg:"subcommand"`
}

arg.MustParse(&args)
```

Then if you run `app pack` then you will get a message like this:

```
Usage: nested pack --something SOMETHING
error: --something is required
```

Unfortunately there is no way to manually print the full help message for a specific subcommand at present.
