### ISSUE TITLE
There is no way to manually print the help or usage text for a specific subcommand

### ISSUE THREAD

**Issue by alexflint** [alexflint/go-arg#135]
Currently, `p.WriteHelp` always writes the help for the top-level command, meaning there is no way to manually print the help message for a specific subcommand.

We could expose the `cmd` struct as `Subcommand` and add `WriteHelpForSubcommand` and `WriteUsageForSubcommand` to the `Parser` struct.

**Comment by samratjha96** [comment]
@alexflint This would be great. Just encountered this where I wanted to write a description and help text for the subcommand as a whole. Exposing the same capabilities to `Subcommand` as the top level command would be great

**Comment by alexflint** [comment]
Thanks for the note, @samratjha96. Just waiting to have some time to do this.

**Comment by alexflint** [comment]
Fixed in #156
