### ISSUE TITLE
Not able to pass variable both with env and arg

### ISSUE THREAD

**Issue by sabuhish** [alexflint/go-arg#141]
Thanks for the great library, you have done great work!

I am having a little issue, when I set struct field with only passing env behavior works as expected I can either take the field from env or argument. That is okay, however, if add a placeholder, help, and short key, the environment variable does not work anymore. Is it suppose to work like this or there is something I am doing wrong.

1) First one works 
```
type config struct {
	AppName     string `arg:"env:AppName"`

}
```
2) cant take the variable from env. 

```	

type config struct {
         AppName  string `arg:"-a, --appname" env:"AppName"  help:"Name of your  app" placeholder:"AppName"`

}
```

**Comment by sabuhish** [comment]
Fixed this

suppose to be like this:
```
AppName  string `arg:"env:AppName, -a, --appname"  help:"Name of your  app" placeholder:"AppName"`

```

**Comment by alexflint** [comment]
Glad you got this sorted out Sabuhi! Thank you for your kind words about
the library.
