### ISSUE TITLE
Support for map[string]string

### ISSUE THREAD

**Issue by amir20** [alexflint/go-arg#148]
Hello, thank you for the great project. I like the simplicity and project is well maintained. 

I want to replace pflags and viper with this project. 

One of my use cases is to support for a map like flag. As an example, `--test foo=bar`. I don’t see this documented. I am guessing it is not supported. 

Thanks in advance.

**Comment by alexflint** [comment]
Thank you for the kind words @amir20.

This seems like a reasonable request. It is not supported right now but I would be happy to add it. I'm not sure how soon I will be able to get to this but I very much enjoy working on this project so perhaps I can find some time soon.

**Comment by amir20** [comment]
That sounds great. I currently have a solution implemented with pflags so here it is in case you find it helpful. I use `ParseQuery` to parse as maps. 

```go
urlValues, err := url.ParseQuery(strings.ReplaceAll(flagValue, ",", "&"))
if err != nil {
	log.Fatal(err)
}
filters = map[string]string{}
for k, v := range urlValues {
	filters[k] = v[0]
}
```

`foo=bar,xyz=yak` becomes `foo=bar&xyz=yak` and then `ParseQuery` handles the rest. 

Hope this is helpful.

**Comment by amir20** [comment]
Thanks. Do you plan to release 1.4.0?

**Comment by alexflint** [comment]
Yes I do @amir20 

You may also be interested in #152, which adds an example of parsing into a map in the case that you want to separate your values by commas, not spaces.

**Comment by amir20** [comment]
Thank you sir. Already sent PR. I saw that you didn't provide comma out of the box. I am ok with that for now.

**Comment by amir20** [comment]
Just for anybody who is interested, the diff for removing viper and pflags and adding go-arg instead was HUGE!

https://github.com/amir20/dozzle/commit/51a74691f931cd22624a7d13e20559eb4f135268

The go.mod files dropped so many modules and I ended up saving about a 1MB on binary

**Comment by alexflint** [comment]
Really great to hear Amir. Thank you for sharing this link. It's really
nice to see examples of the library being integrated.

Yes for comma-separated mappings you could do something like this:
https://github.com/alexflint/go-arg/blob/master/example_test.go#L98-L125

**Comment by amir20** [comment]
@alexflint looks like `""` throw an exception. See https://github.com/amir20/dozzle/issues/1169. Is that expected behavior?

**Comment by alexflint** [comment]
Hmm no definitely not expected. Let me put in a quick fix...

**Comment by alexflint** [comment]
OK I just pushed out v1.4.1 with a fix for this (https://github.com/alexflint/go-arg/releases/tag/v1.4.1)

**Comment by amir20** [comment]
Thank you! Will try it now
