### ISSUE TITLE
Support for map[string][]string

### ISSUE THREAD

**Issue by amir20** [alexflint/go-arg#155]
Hi there again, 

I have a unique situation. My project, Dozzle, has a `--filter` param which was the original intention of #148.  But I guess I had missed something. Dozzle filter tries to map to how Docker works. I am not sure if you know a lot about Docker, but one could do [multiple filters](https://docs.docker.com/engine/reference/commandline/ps/) with `--filter name=foo --filter name=bar`. This essentially turns into a `map[string]map[string]bool` which is a map of set. 

I was planning to implement this myself with [custom parser](https://github.com/alexflint/go-arg#custom-parsing) and `UnmarshalText`. I could probably write a function that parses `name=foo,name=bar` to what I need. But I don't think it would work with `--filter X=y --filter X=a`.  But then I noticed, you do support [multiple](https://github.com/alexflint/go-arg#arguments-that-can-be-specified-multiple-times-mixed-with-positionals) args. 

So two questions: 

1. Given that you already support multiple args for lists, do you think this is something go-arg should support natively with maps? 
2. If not, how could I support with custom parsing to do multiple args with maps?

Maybe there should be support `map[string][]string` which is the only way to support this correctly.

Thanks as always! See https://github.com/amir20/dozzle/issues/293#issuecomment-831844293 for context.

**Comment by alexflint** [comment]
Hi @amir20. I believe you could do this using code something like this.
```go
var args struct {
  Filter []string `arg:"separate"`  // the "separate" tag means that "--filter" can appear multiple times on the command line
}
parser := arg.MustParse(&args)

m := make(map[string][]string)
for _, filter := range args.Filters {
  pos := strings.Index(filter, "=")
  if pos == -1 {
    parser.Fail("each filter should be of the form key=value")
  }
  key := filter[:pos]
  val := filter[pos+1:]
  m[key] = append(m[key], val)
}

fmt.Printf("%#v\n", m)
```

**Comment by alexflint** [comment]
If you want the info to be stored in the struct then you could do something like this:

```go
var args struct {
  FilterStrings []string `arg:"--filter,separate"`
  Filter map[string][]string `arg:"-"` // this tag tells go-arg to ignore this field
}
parser := arg.MustParse(&args)

args.Filter = make(map[string][]string)
for _, filter := range args.FilterStrings {
  pos := strings.Index(filter, "=")
  if pos == -1 {
    parser.Fail("each filter should be of the form key=value")
  }
  key := filter[:pos]
  val := filter[pos+1:]
  args.Filter[key] = append(args.Filter[key], val)
}
```

**Comment by amir20** [comment]
Excellent. I’ll try it tomorrow!

**Comment by amir20** [comment]
Worked great. Seems like env is also handled automatically with `DOZZLE_FILTER=name=foo,name=bar`
