### ISSUE TITLE
Upgrade from go-arg v1.3.0 to v1.4.1 removes flags

### ISSUE THREAD

**Issue by atc0005** [alexflint/go-arg#157]
Hi,

First of all, thanks for your time & effort maintaining this library.

One of my projects received a Dependabot PR to upgrade go-arg from v1.3.0 to v1.4.1. After merging this PR, I received a bug report that binaries built using go-arg v1.4.1 no longer had the expected flags available. Once I backed out the commit representing the v1.3.0 to v1.4.1 upgrade, the expected flags were once again available.

Here is a permalink to a `Config` struct used by my project which embeds `cliConfig` and `fileConfig` structs:

https://github.com/atc0005/query-meta/blob/08cb853cd2068d280b029d43976d8f3197d84e4b/internal/config/types.go#L19

I populate the `fileConfig` struct using a different library and the `cliConfig` struct using this library. For this project I don't do this by directly targeting each embedded struct, but by allowing the struct tags to specify which fields are handled by which library.

Relevant line of the `cliConfig` struct:

https://github.com/atc0005/query-meta/blob/08cb853cd2068d280b029d43976d8f3197d84e4b/internal/config/types.go#L35

Example output from two builds (one with the commit that upgrades go-arg from v1.3.0 to 1.4.1, and one without) is available here:

https://github.com/atc0005/query-meta/issues/15

Please let me know if I can elaborate further, or if this is sufficient to reproduce.

Thanks!

**Comment by alexflint** [comment]
Thank you for this report Adam. I will look into it.

**Comment by alexflint** [comment]
Turns out the issue was that we mistakenly stopped recursing into unexported embedded structs. Sorry about this. Thank you again for your patience.

**Comment by alexflint** [comment]
I have released v1.4.2 containing a patch for this issue. I tested your code with this release and confirmed that the args now show up as expected.

https://github.com/alexflint/go-arg/releases/tag/v1.4.2

**Comment by atc0005** [comment]
@alexflint thanks!
