### ISSUE TITLE
How to enter a positional string that starts with a hyphen?

### ISSUE THREAD

**Issue by kuredoro** [alexflint/go-arg#159]
Here's an MWE:
```
package main

import (
    "fmt"
	"github.com/alexflint/go-arg"
)

type Args struct {
    Args []string `arg:"positional" placeholder:"ARG"`
}

var args Args

func main() {
    arg.MustParse(&args)
    fmt.Printf("Args: %v\n", args.Args)
}
```

If I run it like this, everything's fine:
```
$ go build test.go
$ ./test 1 2 3 4 5
Args: [1 2 3 4 5]
```
But if I enter negative numbers, `arg` issues an error that the flag doesn't exist
```
$ ./test 0 1 2 -2 -1
Usage: test [ARG [ARG ...]]
error: unknown argument -2
```

Is there any way to mitigate this? Maybe prohibit mixing positional arguments with flags or something?

**Comment by kuredoro** [comment]
Here's what I've end up with. My task was to parse the arguments of like `--flag1 --flag2 app_name arguments...` and to forward `arguments...` to the `app_name` when it's launched. The solution I found is to create a custom `arg.Parser` and try to incrementally parse string slices that end with a non-flag string. Assuming that `app_name` is required, the parser will return error, until we've picked `app_name` up after which point only the `arguments...` are left. These are then put inside the array in the Args struct.

```
package main

import (
    "os"
    "fmt"
	"github.com/alexflint/go-arg"
)

type Args struct {
    Flag bool
    AppName string `arg:"positional,required"`
    Args []string `arg:"positional"`
}

var args Args

func mustParse(dest *Args) {
    parser, err := arg.NewParser(arg.Config{}, dest)
    if err != nil {
        fmt.Fprintf(os.Stderr, "error: couldn't initialize command line argument parser")
        os.Exit(-1)
    }

    cliArgs := os.Args[1:]

    for end := 0; end != len(cliArgs)+1; end++ {
        // Skip flags until we find a bare string, possibly the executable.
        // But allow parser.Parse to execute at least once.
        if end != 0 && cliArgs[end-1][0] == '-' {
            continue
        }

        err = parser.Parse(cliArgs[:end])
        if err != nil {
            continue
        }

        dest.Args = cliArgs[end:]
        break
    }

    // It will handle help and version arguments.
    if err != nil {
        arg.MustParse(dest)
    }
}

func main() {
    mustParse(&args)
    fmt.Printf("%#v", args)
}
```

**Comment by alexflint** [comment]
Thank you for posting this thorough issue and the solution you found, @kuredoro 

Just so you know, one other way to achieve this is to put a `--` on the command line, after which all arguments will be treated as positionals:
```bash
./myprogram --flag1 --flag2 app_name -- argument1 argument2 argument3
```
In the above, the three arguments will be treated as positionals even if they start with a hyphen.
