### ISSUE TITLE
Add support for url.URL types

### ISSUE THREAD

**Issue by ryanc414** [alexflint/go-arg#161]
Hi - I was wondering if you would consider adding support for the url.URL type from the stdlib net/url package?

Currently when passing URLs as args with go-arg as far as I can tell there are two options:

1. Declare as a string type and later call url.Parse() and handle the error.
2. Define a custom type which wraps url.URL and implements encoding.TextUnmarshaller via url.Parse().

This is OK but it would be even better if go-arg could handle url.URL types straight out the box!

In an ideal world of course url.URL would already implement encoding.TextUnmarshaller. I find it strange that it doesn't when there is a url.Parse() with a very similar signature, only difference being that it allocates a new object instead of mutating an existing one in-place. Given that this is part of the stdlib I don't think it is very likely/easy to change this type, so given that it is fairly commonly used it might be useful to handle here as a special-case. What do you think? I would be happy to contribute a PR if you like.

Tangentially I couldn't easily find a list of all the supported types in your docs. Am I correct in assuming it is currently just the primitive types plus any others that implement encoding.TextUnmarshaller?

**Comment by alexflint** [comment]
Yep seems reasonable to me. This would need to be a change on [the go-scalar repository](https://github.com/alexflint/go-scalar).

> Tangentially I couldn't easily find a list of all the supported types in your docs.

Indeed this is not well documented at all. The supported types are primitives and TextUnmarshaller, plus mail.Address, time.Duration, and net.HardwareAddr. You can see the code that handles these last three as special cases here:

https://github.com/alexflint/go-scalar/blob/master/scalar.go#L67-L89

And this also shows how support for url.URL could be added.

**Comment by alexflint** [comment]
Just released an update to `go-scalar` that adds support for URLs: https://github.com/alexflint/go-scalar/releases/tag/v1.1.0

I'll need to bump the relevant version line in this repo in order for it to show up when using go-arg.

**Comment by ryanc414** [comment]
Nice one, that was quick!
