### ISSUE TITLE
optional positional arguments should be displayed as such in the Usage string

### ISSUE THREAD

**Issue by chmike** [alexflint/go-arg#174]
Thank you very much for this impressive package. I would like to report a minor problem with the Usage string. 

When defining the following structure and main function:

```Go
type Args struct {
    Arg1 string `arg:"positional,required"`
    Arg2 string `arg:"positional"`
}

func main() {
    var args Args
    arg.MustParse(&args)
}
```

The help output is:
```bash
$ testArgs
Usage: testArgs ARG1 ARG2
error: arg1 is required
```
`go-arg` properly detects that `Arg2` is an optional positional argument, but it is not shown as optional in the usage string.

I was expecting that the Usage string would be `Usage: testArgs ARG1 [ARG2]`.

**Comment by alexflint** [comment]
Yeah I agree. Will take a look into this.

**Comment by alexflint** [comment]
@chmike if you have a moment then would you take a look at #175 and tell me whether this matches your intuition for how usage strings ought to appear?

**Comment by chmike** [comment]
Sorry for the delayed answer. The change is perfect. 

Your package is very impressive. The API is so simple, intuitive and conveinient, it is remarkable. I'll recommend we use it in our project.
