### ISSUE TITLE
New release ?

### ISSUE THREAD

**Issue by chmike** [alexflint/go-arg#176]
Unfortunately, `go get github.com/alexflint/go-arg@latest` installs release 1.4.2 which is one year old and doesn't contain the fix for issue #174 for instance.

Is it possible to provide a new release, please, so that we can benefit from the latest enhancements since release 1.4.2 ?

**Comment by alexflint** [comment]
Done (https://github.com/alexflint/go-arg/releases/tag/v1.4.3)
