### ISSUE TITLE
Disabling argument programmatically?

### ISSUE THREAD

**Issue by IljaN** [alexflint/go-arg#180]
Is there a way to conditionally disable a specific argument? The use case is that "File" should not be required if STDIN is connected.
```golang
type subcommand struct {
	File string `arg:"positional,required"`,  
        ...
}
```

```shell
./app subcommand -x -z < input.json #Error: Required "File" missing
```

- Tried hacking the lib to provide a callback which allows to filter Specs before they are applied (works)
- Ugly workaround with TextUnmarshaller type which ignores the arg value if STDIN is connected.

**Comment by alexflint** [comment]
One thing you could do is make the argument non-required, and then print an error message and usage string later if the argument is missing and STDIN is not connected.

Another option would be to use embedded structs like this:

```
type baseArgs struct {
  ... remaining arguments here ...
}

type args struct {
  baseArgs
  File string `arg:"positional,required"`
}

func main() {
  var args *args
  if (stdin_is_attached) {
    var a baseArgs
    arg.MustParse(&a)
    args = &a.baseArgs
  } else {
    var a args
    arg.MustParse(&a)
    args = &a
  }
}
```

Other than this there is no built-in way to accomplish this with the library.
