### ISSUE TITLE
preamble text to help text ?

### ISSUE THREAD

**Issue by chmike** [alexflint/go-arg#181]
Thank you very much for `go-arg` which is a great and simple way to manage command arguments.

For some application, I would like to be able to add a preamble text in front of the auto generated argument list help message. 
How could I add this ? 

Golang flags has a `Usage` function that can be overridden to customize the help message. Does `go-arg` have something equivalent ?

**Comment by chmike** [comment]
Sorry, just saw that it is done with the description string. Perfect.

**Comment by alexflint** [comment]
Thank you for the kind words @chmike and I'm glad you found the description string feature.
