### ISSUE TITLE
Is it possible to show help message when only the command is entered?

### ISSUE THREAD

**Issue by nosarthur** [alexflint/go-arg#190]
Suppose my main command is called `git`, and normally `git -h` shows the help message. Is it possible to show that without `-h`?

**Comment by alexflint** [comment]
You could do something like this:

```go
var args struct {
  ...
}
p := arg.NewParser(&args)
if (len(os.Args()) == 2) {
  p.WriteUsage(os.Stdout)
  os.Exit(0)
}
err := p.Parse(os.Args())
```

**Comment by alexflint** [comment]
Closing for now. Feel free to re-open if this doesn't solve your problem.

**Comment by dabde** [comment]
Would reopen this issue. Would like to show the whole help output from `-h`, if no argument is supplied. But using `WriteUsage` is return only a short help.

**Comment by alexflint** [comment]
Oh, try using WriteHelp instead

**Comment by dabde** [comment]
Ahh thx.
