### ISSUE TITLE
Can't reimplement MustParse behaviour when using NewParser

### ISSUE THREAD

**Issue by daenney** [alexflint/go-arg#194]
`MustParse` is really helpful: https://github.com/alexflint/go-arg/blob/74af96c6ccf404613c251bca4814d32c69047c5f/parse.go#L85-L95

However, if you want to use a custom `Config`, you have to call `NewParser()` which returns a `*Parser` but hasn't gone through the steps `MustParse` takes. Though I can implement most of `MustParse` myself again by calling `parser.Parse(os.Args)` first and then switching on the resulting `err` like `MustParse` does and calling the exported `WriteHelpForSubcommand()` and `FailWithSubcommand()`.

I can't access `version` and `lastCmd` since those are unexported and there doesn't appear to be an exported equivalent. Version I can still get to using something like `&args.Version()` or having a `func Version()`, but `lastCmd` appears completely unaccessible.

**Comment by alexflint** [comment]
Another way to do it would be to define a `ParseError` struct and put the methods `WriteHelp` and `Fail` on that. Then we would have `p.Parse` return a `*ParseError`. Internally, `ParseError` would store `lastCmd` as well as a pointer back to the `Parser` that produced it.

**Comment by daenney** [comment]
I've been wondering about doing something different. From my point of view, `MustParse` is essentially a shortcut since it creates a parser with the built-in config. But an equivalent method could be available on a `Parser` directly.

So instead of having `MustParse` contain all the logic, I would propose moving that login into a `Must` method on `Parser`. And `MustParse` calls that instead.

Which could mean we'd end up with:

```go
func (p *Parser) Must() {
  err = p.Parse(flags())
  switch {
  case err == ErrHelp:
    p.writeHelpForSubcommand(stdout, p.lastCmd)
    osExit(0)
  case err == ErrVersion:
    fmt.Fprintln(stdout, p.version)
    osExit(0)
  case err != nil:
    p.failWithSubcommand(err.Error(), p.lastCmd)
  }
}
```

And then `MustParse()` becomes:
```go
func MustParse(dest ...interface{}) *Parser {
  p, err := NewParser(Config{}, dest...)
  if err != nil {
    fmt.Fprintln(stdout, err)
    osExit(-1)
    return nil // just in case osExit was monkey-patched
  }
  p.Must()
  
  return p
}
```

I think that solves the issue of not having the equivalent of `MustParse()` available when using `parser.New()`, by moving a bit of code around.

**Comment by alexflint** [comment]
I like that suggestion. Let's call the function `MustParse` though, and have it take in the same arguments that `Parse` takes in, in order to follow the Go convention where calling MustX() is equivalent to calling X() and exiting on error.

**Comment by daenney** [comment]
That doesn't seem to entirely make sense to me. `MustParse()` takes in a `dest ...interface{}` and returns a `*Parser`. `NewParser(config Config, dests ...interface{})` already gives you a `*Parser`, which by itself has already taken in a `dests ...interface{}`. Though we could make a `func (p *Parser) MustParse(dest ...intreface{}) *Parser`, the signature doesn't make much sense to me. I don't think you'd want to pass in additional structs, or return a parser?

**Comment by alexflint** [comment]
Oh no I was suggesting to have it take the same arguments that the `Parse` function on the `Parser` struct takes, i.e. something very close to your comment above:

```go
func (p *Parser) MustParse(args []string) {
  err = p.Parse(args)
  switch {
  case err == ErrHelp:
    p.writeHelpForSubcommand(stdout, p.lastCmd)
    osExit(0)
  case err == ErrVersion:
    fmt.Fprintln(stdout, p.version)
    osExit(0)
  case err != nil:
    p.failWithSubcommand(err.Error(), p.lastCmd)
  }
}
```

**Comment by daenney** [comment]
Ah I see. I misunderstood that. That makes way more sense. I"ll send a PR for it tomorrow.
