### ISSUE TITLE
Epilogues aren't being printed

### ISSUE THREAD

**Issue by daenney** [alexflint/go-arg#199]
Epilogues don't seem to get printed when configured.

I've recreated https://github.com/alexflint/go-arg/blob/dbc2ba5d0c9a6a439d1f825f8c299fb276bbc911/usage_test.go#L288-L317 over on the Go Playground: https://go.dev/play/p/u3Su_WOfls1.

Even though the test in `usage_test` passes, the epilogue is missing in the output as seen on the Go Playground

**Comment by SebastiaanPasterkamp** [comment]
The epilogue feature has not been included in any release yet. If you are interested in running the main branch with this feature instead (or for the time being) you can try the following in your project root:

```shell
go get github.com/alexflint/go-arg@master
go mod tidy
go mod vendor # if you use -mod=vendor
```

**Comment by daenney** [comment]
Ah you're right :facepalm:.
