### ISSUE TITLE
Supporting Docker Secrets

### ISSUE THREAD

**Issue by amir20** [alexflint/go-arg#202]
Hello again,

Would you be open to supporting `#{parameter_name}_FILE` for also reading configurations from a file? I ask because Docker [Secrets](https://docs.docker.com/engine/swarm/secrets/) writes configurations to a file. 

Someone asked on Dozzle if I support this https://github.com/amir20/dozzle/issues/1927

I could support it but maybe this library should also support it. So the logic would be 

1. Try the parameter from cli and look for `--parameter-name`
2. Then try for `PARAMETER_NAME` in ENV
3. Last if if `PARAMETER_NAME_FILE` is set, read that file. 

What do you think?

**Comment by alexflint** [comment]
Yes it's worth considering for this library but just as an interim solution you might do something like this:

```go
type DockerSecret struct {
  Value string
}

func (s *DockerSecret) UnmarshalText(b []byte) error {
  v, err := os.ReadFile(string(b))
  s.Value = string(v)
  return err
}

func main() {
  var args struct {
    Parameter *string `arg:"env:PARAMETER_NAME"`
    ParameterAlt *DockerSecret `arg:"env:PARAMETER_NAME_FILE"`
  }
  arg.MustParse(&args)
  if args.Parameter == nil && args.ParameterAlt != nil {
    args.Parameter = &args.parameterAlt.Value
  }
}
```

Closing for now but I'll tag this as a v2 feature for possible inclusion in #197.
