### ISSUE TITLE
Show usage when no args provided

### ISSUE THREAD

**Issue by suntong** [alexflint/go-arg#212]
```sh
$ ./example
Usage: example --id ID [--timeout TIMEOUT]
error: --id is required
exit status 255
```

I'd like to propose a different behavior than this -- if you run commands like `git`, `rsync` etc _without any command line arguments_, the (default) behavior is to show the usage _only_, instead of reporting errors. 

BTW, both `git` & `rsync` 's return code (exit status) are `1` in such case.

**Comment by suntong** [comment]
```
p := arg.MustParse(&args)
if p.Subcommand() == nil {
    p.Fail("missing subcommand")
}
```

I'd like to show usage instead of reporting errors here as well.  
So maybe the `Usage` function should be exposed for us to call for cases like this. 

thx

**Comment by alexflint** [comment]
You can call `p.WriteUsage(os.Stdout)` to write usage to standard output. To have the thing print usage when no arguments are given, you could do this:

```go
p := arg.MustParse(&args)
if p.Subcommand() == nil {
  p.WriteUsage(os.Stdout)
  fmt.Println("missing subcommand")
  os.Exit(1)
}

**Comment by suntong** [comment]
> You can call `p.WriteUsage(os.Stdout)` to write usage to standard output

I gave it a try as per your help and with the latest version, it seems only print the first line --

`Usage: s-subcommands [--quiet] <command> [<args>]`

whereas I was hoping to print the whole help text:

```
Usage: s-subcommands [--quiet] <command> [<args>]

Options:
  --quiet, -q
  --help, -h             display this help and exit

Commands:
  checkout
  commit
  push
```

BTW, the request in OP still holds -- if to run commands without any command line arguments, better just to show the usage only without reporting errors.

**Comment by alexflint** [comment]
Oops, it should be `p.WriteHelp`, not `p.WriteUsage`

**Comment by suntong** [comment]
Thanks. How about

`./s-subcommands commit`

How to know that if no arguments are given, and how to show the usage for the subcommand only?

**Comment by cgons** [comment]
@suntong - Take a look at the package documentation. Specifically, the following methods:

- https://pkg.go.dev/github.com/alexflint/go-arg#Parser.WriteHelpForSubcommand
- https://pkg.go.dev/github.com/alexflint/go-arg#Parser.WriteUsageForSubcommand

**Comment by suntong** [comment]
thanks!
