### ISSUE TITLE
Manual Help/Usage Printing while obtaining the returned error

### ISSUE THREAD

**Issue by atticus-sullivan** [alexflint/go-arg#217]
Hi,

I just recently found this library and am currently thinking about using it. So far it seems like all things I need are already there (nice job :+1:) except that my requirement regarding interacting with the actual parsing is a bit unusual I think. From a high level view, I want to parse an arbitrary string slice (possible with `parser.Parse` :heavy_check_mark:). In addition, I need to be able to send the help/usage message to an arbitrary buffer (possible with `parser.WriteHelp` or with setting `config.Out`). But with this last point, I've got some troubles. Let's go through the options:

1. `parser.WriteHelp`: The issue here is that this does not work correctly for subcommands. While there exists `WriteHelpForSubcommand`, I'm not sure how to obtain the `subcommand` argument since `parser.lastCmd` is not available (same problem like in https://github.com/alexflint/go-arg/issues/194)  ❌

2. set `config.Out` and use `parser.MustParse` this was the fix in https://github.com/alexflint/go-arg/issues/194. The problem I've got here is that I don't want the program to exit on e.g. `-h`. I know this can be fixed by setting `config.Exit` but then there is no way of detecting if the help output was requested (and therefore avoid evaluating the arguments)  ❌
[the `config.Exit` function might as well set some global variable to be able to check if `Exit` was called, but this is kinda ugly]
[And `parser.MustParse` is not part of the latest release, but this may be fixed by pinning the concrete commit as a dependency]

----
Some Background:
The reason for these requirements is that I use this to build some sort of chat-bot to which I want to pass commandline-like messages.
So at first, the channel to interact with the user is not `os.Stdout`. And second, as the whole process running is a server just `os.Exit`ing if the user requested `help`, is not an option.

**Comment by alexflint** [comment]
Sorry for leaving this for so long without an answer! You can use parser.SubcommandNames() to get the subcommand to pass to WriteHelpForSubcommand. It could look like this:

```go
var args struct { ... }
p := arg.MustParse(&args)
p.WriteHelpForSubcommand(p.SubcommandNames()...)
```
