### ISSUE TITLE
Positional arguments error even when no positionals are specified

### ISSUE THREAD

**Issue by LainesOnTheRun** [alexflint/go-arg#218]
Hello,
I'm confused why I'm getting the following error
```
Usage: main.go [--graceperiod GRACEPERIOD] [--podtimeout PODTIMEOUT] [--features FEATURES]
error: too many positional arguments at 'canary'
```
```
var args struct {
	GracePeriod int64 `arg:"-g,env:GRACE_PERIOD" default:"10"`
	PodTimeout  int64 `arg:"-p,env:POD_TIMEOUT" default:"180"`
	Features    []string 
}
```

**Comment by alexflint** [comment]
It is interpreting the token "canary" as a positional argument, and the error is because your program doesn't accept any positional arguments, so it says that you have given "too many positional arguments". Can you show me the full command you use that includes the "canary" token?

**Comment by marco-m** [comment]
This can happen when passing the whole os.Args:

```go
	cli, err := arg.NewParser(arg.Config{}, &args)
	if err != nil {
		return err
	}
	if err := cli.Parse(os.Args); err != nil {
		return err
	}
```

instead, skip the program name:
```go
	cli, err := arg.NewParser(arg.Config{}, &args)
	if err != nil {
		return err
	}
	if err := cli.Parse(os.Args[1:]); err != nil {
		return err
	}
```

So I think that in the OP case, `canary` is the name of the program. This has happened to me.

Repro:

```go
package main

import (
	"fmt"
	"os"

	"github.com/alexflint/go-arg"
)

func main() {
	if err := run(); err != nil {
		fmt.Println("error:", err)
		os.Exit(1)
	}
}

func run() error {
	var args struct {
		GracePeriod int64 `arg:"-g,env:GRACE_PERIOD" default:"10"`
		PodTimeout  int64 `arg:"-p,env:POD_TIMEOUT" default:"180"`
		Features    []string
	}
	cli, err := arg.NewParser(arg.Config{}, &args)
	if err != nil {
		panic(err)
	}
	if err := cli.Parse(os.Args); err != nil {
		return err
	}
	return nil
}
```

and

```
$ pwd
issue-218
$ go build . && ./issue-218 
error: too many positional arguments at './issue-218'
```

**Comment by tjex** [comment]
I'm also experiencing this. 
Could it be to do with handling `[]string` types?
Although I'm not defining an argument type of `[]string` specifically, the program is iterating over an object of `[]string` via `filepath.Glob(args.Files)` (args.Files is of type `string`).

I get the same error when globbing, but when targeting the file directly, the program works.
The strangest thing though is that it works when executing from within neovim (see below)

```go
package main

import (
	"fmt"
	"github.com/alexflint/go-arg"
	"log"
	"os"
	"path/filepath"
	"strings"
)

var args struct {
        Files       string `arg:"-f" help:"file or dir/* of files"` // can be 1 file
	ToReplace   string `arg:"-t" help:"target char or string to replace"`
	Replacement string `arg:"-r" help:"replacement char or string"`
}

func replaceStringInFile() {
	matches, err := filepath.Glob(args.Files)
	if err != nil {
		log.Fatal(err)
	}

	// apply reanaming to all files
	counter := 0
	for _, match := range matches {
		// check if string exists in file name and apply replacement if so
		if strings.Contains(match, args.ToReplace) {
			counter++
			newName := strings.Replace(match, args.ToReplace, args.Replacement, -1)
			err = os.Rename(match, newName)
			if err != nil {
				fmt.Println("error for file", match, ":", err)
			}
			fmt.Println("renamed", match, "->", newName)
		}
	}
	if counter == 0 {
		fmt.Println("no files with matching string or character found")
	}

}

func main() {
	arg.MustParse(&args)
	replaceStringInFile()

}
```

```tree
.
├── autorun.out
├── go.mod
├── go.sum
├── ignored
│   ├── child
│   │   └── child-file.txt
│   ├── decentralised-chicken
│   ├── parent-file.txt
│   └── test.blah.txt
├── main.go
└── test_file

```
![Screenshot 2023-09-25 at 15 25 26](https://github.com/alexflint/go-arg/assets/83029642/f46f0642-1075-4501-9487-eebe246d495c)

## Neovim

As mentioned if I run it from within neovim via [this autorun command](https://github.com/tjex/dotfiles/blob/79540b6684b9a6ca91fa3b48f37b1654a66b7a89/.config/nvim/lua/tjex/commands.lua) (which just runs the given command `go run main.go -f ignored/* -t=- -r=_` and outputs stdout to a buffer in neovim), it works... 

![Screenshot 2023-09-25 at 15 29 35](https://github.com/alexflint/go-arg/assets/83029642/3a6bd6be-69ed-4069-92cc-e193f0d7c465)

```tree
.
├── autorun.out
├── go.mod
├── go.sum
├── ignored
│   ├── child
│   │   └── child-file.txt
│   ├── decentralised_chicken
│   ├── parent_file.txt
│   └── test.blah.txt
├── main
├── main.go
└── test_file

```

**Comment by alexflint** [comment]
@tjex The reason you're getting this error is that when you type `./main -f ignore/*` on the command line, your shell actually does the glob matching logic and runs the command with a list of the files it finds, so under the hood the program is receiving arguments like this:

```
./main -f ignored/decentralised-chicken ingored/parent-file.txt
```

This gives you the error "too many positional arguments" because in your program, "-f" only accepts one string.

The most common way to deal with this is to not do any glob matching at all in your program, and change your "Files" argument to be a slice of strings:

```go
var args struct {
        Files       []string `arg:"-f" help:"file or dir/* of files"` // can be 1 file
}
```

Then, in replaceStringInFile, you can just iterate over the list of files and you don't need to any glob matching:

```
func replaceStringInFile() {
	// apply reanaming to all files
	counter := 0
	for _, file := range args.Files {
```

The reason it works in neovim with that autorun command is that in that situation you're not using a shell, so the shell glob is not expanded into a list of files, and so the command just receives one argument. If you want it to work correctly in that case then you may keep your current globbing logic in Go, and when you run it from the command line you will have to put your glob in single quotes:

```bash
./main -f "ignored/*'
```

There is a third option for you, which is to handle both situations seamlessly, which you can do by making the argument into a slice of strings, and then applying glob expansion to each of those strings:

```
var args struct {
        FileGlobs       []string `arg:"-f" help:"file or dir/* of files"` // can be 1 file
	ToReplace   string `arg:"-t" help:"target char or string to replace"`
	Replacement string `arg:"-r" help:"replacement char or string"`
}

func replaceStringInFile() {
    for _, glob := range args.FileGlobs {
	matches, err := filepath.Glob(glob)
	if err != nil {
		log.Fatal(err)
	}

	// apply reanaming to all files
	counter := 0
	for _, match := range matches {
		// check if string exists in file name and apply replacement if so
		if strings.Contains(match, args.ToReplace) {
			counter++
			newName := strings.Replace(match, args.ToReplace, args.Replacement, -1)
			err = os.Rename(match, newName)
			if err != nil {
				fmt.Println("error for file", match, ":", err)
			}
			fmt.Println("renamed", match, "->", newName)
		}
	}
	if counter == 0 {
		fmt.Println("no files with matching string or character found")
	}
    }
}
```

Hope this helps. Closing the issue for now.

**Comment by tjex** [comment]
working! thanks so much for the extra info and examples! most definitely solved for me 🙏
