### ISSUE TITLE
passing command line arguments into used packages

### ISSUE THREAD

**Issue by wit-go** [alexflint/go-arg#220]
I have packages that I'm using that I want to send arguments inside the packages. I tried to do trick it into reading the values passed in the init() functions in an included package but couldn't figure out how to make that work.

Maybe there could be a standard call developed so that a package can read the values set on the command line in the package init() function? I wasn't going to try to figure out how to make a patch for that if you already knew you didn't want one or knew why it wasn't possible.

**Comment by alexflint** [comment]
The best way would be to use embedded structs. In one package you can define a struct like this:

```go
package abc

type SomeArgs struct {
  SomeArgument string
}
```

and then in another package -- possibly the "main" package -- you can do this:

```
package main

func main() {
  var args struct {
     ArgumentForThisPackage string
     abc.SomeArgs
  }
  arg.MustParse(&args)
}
```

Now in order to send the arguments to the "abc" package, you might add something like this:

```go
package abc

...

var Args SomeArgs
```

and then in the main package you would add:

```go
package main

...


```go
package main

func main() {
  ...
  abc.Args = args.SomeArgs
}
```

Closing for now. Feel free to re-open if you have further questions.

**Comment by wit-go** [comment]
Let me again say, I hope your go-arg package gets accepted as the default way to handle command line arguments in golang. There should be a standard here.

How I think this should work is -- let's say I have a program called "mysync" and another program called "watchit". They both use mybuf and mygui packages.

I want to maintain the "mygui" package and have --gui <gtk,qt> for example. That will, from the command line, let the user pick which toolkit to use. For the "mybuf" package, let's say I have some command line options that might set protobuf settings for something or another.

If people use the packages in their programs and use 'go-arg' from you, I want the packages to expose those options without having to pass or even know about the options passed into that packages.

I think there should be a way for a package manager to define command line options that are exposed automatically from the user. Obviously there can be conversations of name collisions and the dreaded "death by options" problem, but I believe as a community we will solve those in reasonable ways so that `myftpthing --help` doesn't have 10000 lines of gtk, socket, etc options.

This is a problem that was not really ever solved in traditional linux binaries. For example, you can see from `firefox --help` that, while it mentions that there is "X11 Options", these are obviously not from X11, much less certainly not options that might make sense to expose from either gtk or qt or whatever window manager the user might be using.

Could it be possible to implement this somehow so it can be enabled in the application code? Something that allows go-arg to automatically insert all command line options that the package developer wishes to expose?

I tried to do this in the package init() function but I just am not good enough at GO as a language to understand what is possible. I'm still a very green GO developer I'm afraid.

**Comment by alexflint** [comment]
It's a very interesting question, and a good use case to support. There is a little-known feature of go-arg that may help to solve this use case: The arg.MustParse function can actually accept multiple destination structs, like this:

```go
var args1 struct { ... some arguments here ... }
var args2 struct { ... more arguments here ...}
var args3 struct { ... even more arguments here ... }
arg.MustParse(&args1, &args2, &args3)
```

If there were a way for each package to register its arguments then we could use the above feature of MustParse to send arguments out to each imported library. Suppose we had a new package `pkgargs` with a Register function that could be used like this:

```go
package mypackage
var args struct {
   ... define arguments for this package here ...
}
func init() {
    pkgarg.Regsiter(&args)
}
```

Then the main function could be like this:

```
package main

func main() {
    arg.MustParse(pkgarg.All()...)
}
```

where `pkgargs.All()` is a function in pkgargs that returns all the structs that have been registered. In this way the main function wouldn't have to hardcode a list of destination packages.

Another benefit of this approach is that we would introduce a new package `go-pkgarg` to implement the package-based way of doing things, in order that the API for the core go-arg doesn't get too complex.

One issue here is that if the package-level arguments include positional arguments then things will get a little messy as the order of those positionals will change with the order that each package's init() function is called. It might be better to disallow positional arguments in structs passed to pkgarg.Register.

Interested in your thoughts.

**Comment by wit-go** [comment]
Yes -- this seems right!

``This seems to work in parse.go :
var more []interface{}

func Register(dest ...interface{}) {
        more = append(more, dest...)
}

func MustParse(dest ...interface{}) *Parser {
        dest = append(dest, more...)
`

I added that (more or less) and I think it's working! This is a great improvement.

**Comment by alexflint** [comment]
It's a nice hack but I would never want to bake something like that into the main go-arg package because it'd produce a lot of surprising results if someone were to import a package without realizing that it made use of this facility. Instead it may be wise to create a separate go-pkgarg library that provides this facility.

**Comment by wit-go** [comment]
Sure, I understand. How about this then:

arg.UseRegister()
arg.MustParse()

That way, nothing will change for anyone unless they specifically enable it. I will make a repo to evaluate.
