### ISSUE TITLE
Parsing of type rune does not work

### ISSUE THREAD

**Issue by josipsumeckispread** [alexflint/go-arg#221]
If I have a struct:
```
type AppConfig struct {
	CsvValueSeparatorChar rune    `arg:"-s,--csv-value-separator-char,env:CSV_VALUE_SEPARATOR_CHAR" default:"," help:"CSV format value separator character"`
	CsvLineCommentChar    rune    `arg:"-c,--csv-line-comment-char,env:CSV_LINE_COMMENT_CHAR" default:"#" help:"CSV format line comment character (must be a first character in line)"`
}
```
parser will produce following error:
```
error processing default value for --csv-value-separator-char: strconv.ParseInt: parsing \",\": invalid syntax
```
when no input argument is defined (default value). It also doesn't work with command line argument `-s=';'`.

**Comment by josipsumeckispread** [comment]
Additional info:
```
% go version  
go version go1.20.4 darwin/amd64
```

I guess that this module does not differentiate between `rune` and integer type.
I also checked the source code and `rune` type is not mentioned anywhere in branching and never tested for input.

**Comment by alexflint** [comment]
Fascinating. This does seem like a bug. I'll look at getting in a fix.

**Comment by alexflint** [comment]
Well as far as I can tell, it's not actually possible to distinguish runes from int32 through reflection! Really surprising. The docs say this:

> rune is an alias for int32 and is equivalent to int32 in all ways. It is used, by convention, to distinguish character values from integer values. (https://pkg.go.dev/builtin#rune)

and I just confirmed that if I change the logic for runes, then it also applies to int32 values, and there doesn't seem to be any workaround.

I suggest creating a type like this:

```go
type Rune rune

func (r *Rune) UnmarshalText(b []byte) error {
		if n := utf8.RuneCount(b); n != 1 {
			return fmt.Errorf("error parsing rune: expected string of length 1 but got %q of length %d", string(b), n)
		}
		*r, _ := utf8.DecodeRuneInString(s)
		if *r == utf8.RuneError {
			return fmt.Errorf("error decoding rune from string %q: utf8 error", string(b))
		}
		return nil
}
```

**Comment by josipsumeckispread** [comment]
Thanks @alexflint. This is a great go module. It has much more configuration options than any other module with similar functionality and it is much easier to use it. I would rather have small issues fixed here than switch to another module.

**Comment by alexflint** [comment]
Great. I will close for now but feel free to re-open if you find that there is a way (any way!) to detect rune types within the library, or if the `Rune` type I posted above doesn't work for you.
