### ISSUE TITLE
Struct argument support

### ISSUE THREAD

**Issue by toothrot** [alexflint/go-arg#23]
I've been working on moving all of our projects to go-arg, as it makes way more sense than `flag`. We use nested structs in `flag` in order to be able to re-use flag configuration between different CLI commands. Additionally, we also sometimes use a struct directly from another class as a CLI flag.

For example:

``` go
type DatabaseOptions struct {
    Host string `arg:"required"`
    Port string `arg:"help:Port to connect to the database"`
}

type Options struct {
    Verbose bool `arg:"help:Be noisy"`
    DatabaseOptions
}
```

``` bash
fooApp --host bar --port 123
```

This allows us to have common `DatabaseOptions` throughout our codebase, and to be able to have `go-arg` parse them for us.

The following would be nice to have as well:

``` go
type Options struct {
    Verbose bool `arg:"help:Be noisy"`
    Database DatabaseOptions
}
```

``` bash
fooApp --database-host bar --database-port 123
```

**Comment by alexflint** [comment]
Yep I agree that this should be supported. I'm not sure about automatically putting in a prefix in the case of a nested struct but perhaps there could be a `prefix:database-` tag.

**Comment by brentp** [comment]
This would be nice to have the embedded struct support. In my example use-case, I already have an Options struct that I must replicate (and add the 1 or 2 additional fields) and then, after parsing copy each field back manually in order to use in in the original prog.

**Comment by alexflint** [comment]
@brentp @toothrot 

Okay here is the embedded struct pr: https://github.com/alexflint/go-arg/pull/39. Let me know if you have any comments, otherwise I'll merge this tomorrow.

**Comment by brentp** [comment]
looks great. thank you.
