### ISSUE TITLE
How slice is supposed to work

### ISSUE THREAD

**Issue by lzap** [alexflint/go-arg#235]
Hello,

I have the following struct:

```
type systemDeployCmd struct {
	Pattern     string   `arg:"positional,required" placeholder:"MAC_OR_NAME"`
	Image       string   `arg:"-i,required"`
	Snippets    []string `arg:"-s"`
	TextSnippet string   `arg:"-x"`
	Kickstart   string   `arg:"-k" placeholder:"KS_OVERRIDE_CONTENTS"`
	Comment     string   `arg:"-c"`
	Duration    string   `arg:"-d" default:"3h"`
}
```

It works when I use snippets option as the last:

```
./forester-cli system deploy -i eln-bootc SYSTEM_42123 -s InsecureRootPw
```

However, when positional argument is last it does not work:

```
./forester-cli system deploy -i eln-bootc -s InsecureRootPw SYSTEM_42123
Usage: forester-cli system deploy --image IMAGE [--snippets SNIPPETS] [--textsnippet TEXTSNIPPET] [--kickstart KS_OVERRIDE_CONTENTS] [--comment COMMENT] [--duration DURATION] MAC_OR_NAME
error: pattern is required
```

Can you explain what am I missing here? I do not understand why is that. Thanks.

**Comment by alexflint** [comment]
Ah, good question. By default, slice arguments consume all command line strings from the point that the user wrote `-s` to the end of the command line. So in your last example, you will find that Snippets contains two strings: "InsecureRootPw" and "SYSTEM_42123".

One way you can change this default behavior is by putting the tag `separate` into the Snippets field:
```go
type systemDeployCmd {
  ...
  Snippets []string `arg:"-s,separate"`
  ...
}
```

Then the user will have to put a `-s` for each snippet on the command line:
```
./forester-cli system deploy -s Snippet1 -s Snippet2 -s Snippet3
```

And in this way you can put the positional argument at the end as in your example and it will work as you expect.

**Comment by lzap** [comment]
Oh I had to miss this feature, awesome. Thanks for this great library, it is so clean. Cheers.
