### ISSUE TITLE
Why --help and -h flags don't work while using arg.Parse(&args)

### ISSUE THREAD

**Issue by uynilo9** [alexflint/go-arg#251]
As the title, `arg.Parse(&args)` always return `ErrHelp` after getting `--help` and `-h` flags. Is this what the program is supposed to do?
And how to make it work (print help interface after getting `--help` and `-h` flags) by using `arg.Parse(&args)` rather than `arg.MustParse(&args)`?

Thanks for helping <3

**Comment by alexflint** [comment]
You should do something like

```go
p, err := arg.Parse(&args)
if err == arg.ErrHelp {
    p.WriteHelp(os.Stdout)
}
```
