### ISSUE TITLE
[bug] crash on errors in v1.5.0

### ISSUE THREAD

**Issue by hhromic** [alexflint/go-arg#254]
Today I noticed that `go-arg` is crashing on errors in `v1.5.0`, which did not happen in `v1.4.3` (previous version).

Consider the following minimal reproduction example:
```go
package main

import "github.com/alexflint/go-arg"

var args struct {
	Foo []string `default:""`
}

func main() {
	arg.MustParse(&args)
}
```
**Important:** Note that the struct-tag is invalid because `default` is not supported for slices.

When the above MRE is run with `v1.5.0`:
```
$ go get github.com/alexflint/go-arg@v1.5.0
$ go run main.go
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x4a1cce]

goroutine 1 [running]:
fmt.Fprintln({0x0, 0x0}, {0xc00011be98, 0x1, 0x1})
        /opt/go/src/fmt/print.go:305 +0x4e
github.com/alexflint/go-arg.mustParse({{0x0, 0x0}, 0x0, 0x0, 0x0, 0x4fa540, {0x0, 0x0}}, {0xc000059f30, 0x1, ...})
        /home/hhromic/go/pkg/mod/github.com/alexflint/go-arg@v1.5.0/parse.go:91 +0xe5
github.com/alexflint/go-arg.MustParse(...)
        /home/hhromic/go/pkg/mod/github.com/alexflint/go-arg@v1.5.0/parse.go:84
main.main()
        /home/hhromic/repro/main.go:10 +0x8e
exit status 2
```

However, when run with `v1.4.3`:
```
$ go get github.com/alexflint/go-arg@v1.4.3
go: downgraded github.com/alexflint/go-arg v1.5.0 => v1.4.3
$ go run main.go
.Foo: default values are not supported for slice or map fields
exit status 255
```
Then `go-arg` correctly reports the error.

The problem seems to be in `MustParse` and `mustParse` (the crash happens in line 91):
https://github.com/alexflint/go-arg/blob/dfca71d1594a749ef5e2203e84cfb5a1b8e9387b/parse.go#L82-L98

It can be seen that `MustParse` initializes the `Config` struct without `Out`, which remains as `nil`.

The initialization of `Out` seems to be done in `NewParser`:
https://github.com/alexflint/go-arg/blob/dfca71d1594a749ef5e2203e84cfb5a1b8e9387b/parse.go#L198-L207

However, the `config` argument is NOT a pointer, and therefore all changes made to it by `NewParser` remain local.

**Comment by alexflint** [comment]
Goodness gracious thanks for catching this, and thanks for the PR. Just pushed v1.5.1 with this fix.
