### ISSUE TITLE
de-couple output from MustParse and exiting

### ISSUE THREAD

**Issue by gregwebs** [alexflint/go-arg#267]
If I don't want to exit immediately but I do want to print out help this is what I came up with. It would be great if there was a separate API for getting help output or argument error output.

```go
func flags() []string {
	if len(os.Args) == 0 { // os.Args could be empty
		return nil
	}
	return os.Args[1:]
}

if err := arg.Parse(args); err != nil {
    conf := arg.Config{Out: os.Stdout, Exit: func(int) {}}
    p, errParser := arg.NewParser(conf, &_args)
    if errParser != nil {
       return errParser
    }
    p.MustParse(flags())
}
```

**Comment by alexflint** [comment]
Hey @gregwebs have you looked at Parser.Parse, Parser.WriteHelp and Parser.WriteUsage?

https://pkg.go.dev/github.com/alexflint/go-arg#Parser.Parse
https://pkg.go.dev/github.com/alexflint/go-arg#Parser.WriteHelp
https://pkg.go.dev/github.com/alexflint/go-arg#Parser.WriteUsage

The Parse function will process command line arguments like MustParse, but will return an error rather than exiting. In the case that the return value is arg.ErrHelp, you can use WriteHelp and WriteUsage to print the help text.

These are functions you can call on the `p` variable in your example.

**Comment by gregwebs** [comment]
MustParse is using public functions but it uses non-public fields like `p.subcommand`.

```go
func (p *Parser) MustParse(args []string) {
	err := p.Parse(args)
	switch {
	case err == ErrHelp:
		p.WriteHelpForSubcommand(p.config.Out, p.subcommand...)
		p.config.Exit(0)
	case err == ErrVersion:
		fmt.Fprintln(p.config.Out, p.version)
		p.config.Exit(0)
	case err != nil:
		p.FailSubcommand(err.Error(), p.subcommand...)
	}
}
```

So I am not quite sure how to duplicate it with existing public APIs.
`MustParse` is side-effecting both in writing to output and terminating the program and has the logic for what to do in response to errors and it parses- it would be nice to break this all up into 3 separate functions and not need to configure a fake Exit function.

**Comment by alexflint** [comment]
Regarding use of p.subcommand, you can actually use p.SubcommandNames() to get the same thing from outside  -- it's implementation is [here](https://github.com/alexflint/go-arg/blob/v1.5.1/subcommand.go#L24). Sorry this isn't easy to find.

I'm don't think that p.version is exposed directly, but it's just an arbitrary version string that you would have passed in by implementing a Version() function, or empty. Sorry this isn't very well documented.

Regarding breaking MustParse up into three functions, how would you do it?

**Comment by gregwebs** [comment]
Thanks, that README example is great!

In terms of refactoring things- I think that using the `Parse` function is the way to go. Then there could be a function `WriteHelp(w io.Writer, err error)` and `ExitCode(err error) int`. So

```go
if err := arg.Parse(&args); err != nil {
   arg.WriteHelp(os.Stdout, err)
   os.Exit(arg.ExitCode(err))
}
```

This puts the user in control of all the side effects. The library just does the parsing.
