### ISSUE TITLE
Inconsistent positional arg name case in error output

### ISSUE THREAD

**Issue by powerman** [alexflint/go-arg#275]
```go
var args = struct {
	FirstName  int `arg:"positional,required"`
	SecondName int `arg:"positional,required" placeholder:"<second>"`
}
```
result in these messages:

> Usage: cli **FIRSTNAME** **&lt;second>**
> error: **firstname** is required
> error: error processing **FirstName**: strconv.ParseInt: parsing "bad": invalid syntax
> error: **secondname** is required
> error: error processing **SecondName**: strconv.ParseInt: parsing "bad": invalid syntax

As you see, it uses 3 different casing for arg names.

I propose to change this, to make it use a placeholder value everywhere (i.e. either upper case by default or one provided by user). This way output should be:

> Usage: cli **FIRSTNAME** **&lt;second>**
> error: **FIRSTNAME** is required
> error: error processing **FIRSTNAME**: strconv.ParseInt: parsing "bad": invalid syntax
> error: **&lt;second>** is required
> error: error processing **&lt;second>**: strconv.ParseInt: parsing "bad": invalid syntax

**Comment by alexflint** [comment]
Oh that would be great!

**Comment by zanvd** [comment]
Prepared a PR.

**Comment by zanvd** [comment]
Can this be closed now or should the new version be released first?

**Comment by alexflint** [comment]
Thanks, this can be closed @zanvd
