### ISSUE TITLE
support for version string in help

### ISSUE THREAD

**Issue by brentp** [alexflint/go-arg#37]
would be nice if the struct met some interface, e.g.
```
type Versioned interface {
    Version() string
}
```
then the help would print the version string somewhere in the help.

**Comment by alexflint** [comment]
Nice idea, I think I might implement that

**Comment by alexflint** [comment]
@brentp let me know if you have any thoughts on #37, otherwise I'll merge tomorrow.

**Comment by brentp** [comment]
looks good to me. Thanks!

**Comment by brentp** [comment]
added in #38
