### ISSUE TITLE
Default value vs required arg

### ISSUE THREAD

**Issue by SchulteMarkus** [alexflint/go-arg#40]
go-arg supports [Default values](https://github.com/alexflint/go-arg#default-values). [Required arguments](https://github.com/alexflint/go-arg#required-arguments) are supported, too.

Here is a slightly modified example:

    package main

    import "github.com/alexflint/go-arg"

    var args struct {
	    Foo string `arg:"required"`
	    Bar bool
    }

    func main() {
	    args.Foo = "default value"
	    arg.MustParse(&args)
    }

**Is**: 

    usage: Build main.go and rungo --foo FOO [--bar]
    error: --foo is required

**Should be**: As "foo" is set, I would expect the arguments to be parsed.

**Comment by alexflint** [comment]
If I understand you correctly @SchulteMarkus you're saying that if a required argument has a default value but is not present on the command line then no error should be generated. I agree this is an ambiguous case given the current API. Is there any reason you can't just remove the `required` tag from the arguments that have default values? Can you give me some more context on what you're trying to achieve?

**Comment by SchulteMarkus** [comment]
You do understand me correctly :-) I can remove the `required` tag of course, this is the way i work around this requirement right now. But there are use-cases, where I want to set a default value on a `required` argument. 
While using go-arg, I experienced two use-cases
1. I want to unit-test my go-arg-entity (like struct "args" from above) to be parseable at all. 
2. I am combining go-arg with https://github.com/caarlos0/env. A required argument can be set via command line, or via environment variable. Right now, as go-arg seems to check CLI-input, not struct-state, though I am setting my argument via environment-variable, go-arg still fails.

```
    import "github.com/caarlos0/env"

    func main() {
	env.Parse(&args)
        arg.MustParse(&args)
    }
```

**Comment by alexflint** [comment]
Yes that does seem reasonable. I will take a look at making this change.

By the way, for the first case you can actually use the following

```
type args struct { ... }
_, err := arg.NewParser(arg.Config{}, args{})
if err != nil {
  // test failure...
}
```
