### ISSUE TITLE
[]string as non-positional argument

### ISSUE THREAD

**Issue by kenshaw** [alexflint/go-arg#49]
When using `[]string` as the type for a non-positional argument, for example:

```go
type MyArgs struct {
    Commands []string `arg:"-c,help:commands to execute"`
}
```

The syntax that is usable, is the following: `-c "command1" "command2"`, however one would expect this to behave similar to how other standard command line apps do it: `-c "command1" -c "command2"`.

Here is some example output from `usql` which is using `go-arg` and for which I'd like to accomplish the same style syntax as `psql` (which is also the same as bash and other standard cli programs):

```sh
ken@ken-desktop:~/src/go/src/github.com/knq/usql$ ./usql pg://booktest:booktest@localhost/ -c 'select * from books;' -c 'select * from authors'
2017/03/03 12:41:52 >>> commands: [select * from authors]
  author_id |      name       
+-----------+----------------+
          1 | Unknown Master  
(1 rows)

ken@ken-desktop:~/src/go/src/github.com/knq/usql$ ./usql pg://booktest:booktest@localhost/ -c='select * from books;' -c='select * from authors'
2017/03/03 12:42:00 >>> commands: [select * from authors]
  author_id |      name       
+-----------+----------------+
          1 | Unknown Master  
(1 rows)

ken@ken-desktop:~/src/go/src/github.com/knq/usql$ ./usql pg://booktest:booktest@localhost/ -c 'select * from books;' 'select * from authors'
2017/03/03 12:42:11 >>> commands: [select * from books; select * from authors]
  book_id | author_id | isbn | booktype |        title         | year |            available             |      tags        
+---------+-----------+------+----------+----------------------+------+----------------------------------+-----------------+
        1 |         1 |    1 | FICTION  | my book title        | 2016 | 2017-03-03T00:21:37.613263+07:00 | {}               
        2 |         1 |    2 | FICTION  | changed second title | 2016 | 2017-03-03T00:21:37.613263+07:00 | {cool,disastor}  
        3 |         1 |    3 | FICTION  | the third book       | 2001 | 2017-03-03T00:21:37.613263+07:00 | {cool}           
(3 rows)

  author_id |      name       
+-----------+----------------+
          1 | Unknown Master  
(1 rows)
```

As you can see above, the parsing for `[]string` seems to be the same as a positional argument only. Ideally, one should be able to mix and match the named parameters, and positional arguments:

```sh
$ usql -c 'command1' pg://database -c 'command2'

# the above should work the same as the following:
$ usql -c 'command1' -c 'command2' pg://database
```

I'm happy to do the work for this, but would like approval first to know if I write the PR, it would be accepted. Thanks in advance!

**Comment by kenshaw** [comment]
Please note you can see the code base I'm trying to get up and running with this style of arguments here: https://github.com/knq/usql

Again, thanks! Really appreciate all the work that's been done on `go-arg`.

**Comment by alexflint** [comment]
Thanks for the thoughtful writeup @kenshaw. I thought a little about this a while ago and decided that it would be too difficult to pin down the exact semantics of multiple instances of mult-value arguments. For example, suppose you have
```
type args struct {
  Foo []string
  Bar string `arg:"positional"`
}
```
Then how should the following be interpreted?
```
./prog --foo a b
./prog --foo a b --foo c
./prog x --foo a b
./prog x --foo a b --foo c
```
If you want (2) to be interpreted as `Foo=[a c] Bar=b` then it seems like (1) should be interpreted as `Foo=[a] Bar=b`, but then that would break backwards compatibility with existing behavior.

Alternatively you could interpret (2) as `Foo=[a b c]` but that seems a bit confusing.

I'm open to fixing this but I want to make sure that there are a clear set of semantics to aim for first.

**Comment by kenshaw** [comment]
Yes, agree. It's hard to model every behavior. I think a simple option to toggle the different parsing in the `arg` tag would be prudent. Like:

```go
type MyArgs struct {
   Commands []string `arg:"-c,single,help:command(s) to execute"`
}
```

When setting the `single` option (or whatever) then the expectation is it would read exactly 1 -- alternatively, have something like `,count:2,` where you could read the next N following arguments into the slice.
