### ISSUE TITLE
Positional arguments with dashes

### ISSUE THREAD

**Issue by cirocosta** [alexflint/go-arg#55]
Hey,

I was wondering wether it's possible to a `[]string` as the destination of positional arguments that may container `-`prefixed strings. My use case is `./my-bin --debug my_first_pos_arg -something` where I expect the `[]string{"my_first_pos_arg", "-something"}` to be retrieved as the positional arguments given that I have something like 

```go
type Something struct {
    Debug      bool     `arg:"-d"`
    Positional []string `arg:"positional"`
}
```

Is this possible to be consumed by `go-arg`?
 
Also, thanks a lot for `go-arg`! It's my go-to every time I need something quick and simple :+1: 

Thx!

**Comment by alexflint** [comment]
The only way to do this is by writing
```
./my-bin --debug -- my_first_pos_arg -something
```
Everything after `--` is treated as a positional argument.

**Comment by cirocosta** [comment]
Oh, it works like a charm! Thanks a bunch @alexflint !
