### ISSUE TITLE
switch to the newer 'dep' depepdency tool

### ISSUE THREAD

**Issue by rickb777** [alexflint/go-arg#58]
The `dep` tool is likely to become the standard versioning tool. It would be easy to drop it in in place of godep.

https://github.com/golang/dep

Also, IMHO, the vendored dependencies shouldn't be in the git repo of go-arg. Including them in git forces go-arg users to have multiple copies of dependencies in many cases. Instead they should be in .gitignore and fetched uniformly via `dep ensure`. (This question is broadly a matter of opinion, but for small apis such as go-arg I think the balance is in favour of relying on `dep` instead of using git.)

**Comment by alexflint** [comment]
Agreed, but I think the appropriate time to make the change within `go-arg` will be when `dep` officially becomes the standard versioning tool.
