### ISSUE TITLE
Parse nested sctructs

### ISSUE THREAD

**Issue by SergeAx** [alexflint/go-arg#67]
Can you be interested in adding recursive struct parsing, like in:

```go
var args struct {
	Db struct {
		User		string
		Password	string
	}
	Log struct {
		Enable	bool
		Level	string
	}
}

arg.MustParse(&args)
db := Db.Open(args.Db)
logger := Log.Open(args.Log)
```

```sh
$ app --db.user=guest --db.password=guest --log.level=debug
```

I am fiddling with the idea and would like to implement it, if such PR has chance to be merged.

**Comment by SergeAx** [comment]
@aspcartman 

Currently using structs in `go-arg` is like this:

```go
type DbArgs struct {
	User		string
	Password string
}

type LogArgs struct {
	Enable	bool
	Level	string
}

var args struct {
	DbArgs
	LogArgs
}
```

As you can see, it's kinda anonymous (not named).

> $ app --user guest # where would "guest" end up?

Nowhere. When using named nested structures you should prepend parameter with struct's name via dot.

**Comment by alexflint** [comment]
Yes I'm open to this. Perhaps using a special prefix tag, like this:

```go
type DBArgs struct {
  User string
  Password string
}

var args struct {
  DB DBArgs `arg:"db."`
}
```

Note that the prefix includes the dot ".", so you could also do "db-" if you prefer namespacing via hyphens.

As @aspcartman mentioned, this should not break the existing behavior of nested structs, which is to default to no prefix.

**Comment by alexflint** [comment]
After considering this some more I think this feature would add too much complexity for how widely it would end up being used. Feel free to re-open this issue if you would like to discuss further.
