### ISSUE TITLE
Interested in YAML/JSON configuration?

### ISSUE THREAD

**Issue by ldelossa** [alexflint/go-arg#71]
Hey there, 

So far go-arg is hitting all the sweet spots with flag and env variable parsing. I am curious however do you see JSON and YAML configuration file parsing/generation as a welcome addition to this library? If so I'd take a stab at following the patterns you provide and implementing it. However if you feel that is out of scope for go-arg I will fork and maintain. 

Let me know your thoughts! thanks.

**Comment by alexflint** [comment]
Happy to hear that @ldelossa! I think this is outside the scope of go-arg.
