### ISSUE TITLE
Help Option Text

### ISSUE THREAD

**Issue by runeimp** [alexflint/go-arg#76]
Thank you for this library! 😃

I would like a way to be able to use my own text for the help flags though. Also to be able to specify my own short flag. Either by being able to specify my own explicit Help field

```go
type args struct {
	Debug bool `arg:"-D" help:"Output debug info."`
	Help  bool `arg:"-H" help:"Display this help info."`
}
```
Or by method call such as:

```go
arg.HelpOption("Display this help info.", "-H")
```

or something along the lines of

```go
arg.SetHelpText("Display this help info.")
arg.SetHelpShort("-H")
```

**Comment by alexflint** [comment]
Hey @runeimp, the suggestion you made is actually already implemented:

```
type args struct {
	Debug bool `arg:"-D" help:"Output debug info."`
	Help  bool `arg:"-H" help:"Display this help info."`
}
```

should work just as you describe. Feel free to reopen if this doesn't work for you.
