### ISSUE TITLE
Misleading "Usage:" when slice option and positional arguments?

### ISSUE THREAD

**Issue by marco-m** [alexflint/go-arg#89]
Hello, thanks a lot for go-arg, I love it!

consider the following program (using go-arg v1.1.0)

```go
package main

import (
	"fmt"
	arg "github.com/alexflint/go-arg"
)

func main() {
	var args struct {
		Foo []string
		A   string `arg:"positional,required"`
	}
	arg.MustParse(&args)
	fmt.Printf("%+v\n", args)
}
```

Let's ask for its help:

```console
$ ./bin/positional -h
Usage: positional [--foo FOO] A

Positional arguments:
  A

Options:
  --foo FOO
  --help, -h             display this help and exit
```

If I try to follow the "Usage" example, I get:

```console
$ ./bin/positional --foo 1 x
Usage: positional [--foo FOO] A
error: a is required
```

which is very confusing for the end user (and at first for the programmer too, then the programmer understands the reason :-D)

After thinking about it, I tried the classic `--` to mean end of flag processing, but it didn't work:

```console
 $ ./bin/positional --foo 1 -- x
Usage: positional [--foo FOO] A
error: a is required
```

After a while I saw the light and inverted the order, and it worked as expected:

```console
$ ./bin/positional x --foo 1
{Foo:[1] A:x}
```

So I guess I have two questions:

1. Would it be possible/suitable to make the `--` trick work? (Is this maybe a regression of #55 ?)
2. Would it make sense, in presence of a required positional argument AND a slice of options, to invert the usage, something like:
```
Usage: positional A [--foo FOO]
```
or any other way to give an hint to the user?

**Comment by alexflint** [comment]
Woah this is definitely a bug. Both of the examples you gave are supposed to work:
```
./bin/positional --foo 1 x
./bin/positional --foo 1 -- x
```
If these are broken then go-arg has a regression in a recent release. I'll investigate.

**Comment by alexflint** [comment]
Oh on first read I didn't see that foo is a `[]string`. Given that, I still expect the second example you gave to work (but not the first):
```
./bin/positional --foo 1 -- x   // is supposed to work given the program you gave
./bin/positional --foo 1 x     // not expected to work
```

**Comment by marco-m** [comment]
Would it make sense then to change the usage text to mention the `--` if the positional is required?

```
Usage: positional [--foo FOO] -- A
```
