### ISSUE TITLE
Feature request: optionally toggle environment variable handling on/off

### ISSUE THREAD

**Issue by atc0005** [alexflint/go-arg#95]
As discussed on #94, please consider adding the option to toggle environment variables support in this package. It could be useful to only evaluate flags, disregarding any environment variables that are set. This would allow parsing them with another package in order to change the configuration precedence.

Thank you in advance for your consideration.

**Comment by atc0005** [comment]
@alexflint Thanks for considering and including this feature!

**Comment by alexflint** [comment]
You're very welcome!
