### ISSUE TITLE
Attempts to use go-arg in tests: "error: unknown argument -test.timeout=10m0s"

### ISSUE THREAD

**Issue by atc0005** [alexflint/go-arg#97]
I'm doing something wrong, but I don't know enough to spot the exact cause. Is this is bug with the package or something I'm doing due to my being new to Go testing?

Example:

```golang
package main

import (
	"os"
	"testing"

	"github.com/alexflint/go-arg"
)

type TestConfig struct {
	Option1 int  `arg:"--age,env:TESTING_OPTION1" help:"Placeholder for option 1"`
	Option2 bool `arg:"--keep-old,env:TESTING_OPTION2" help:"Placeholder for option 2"`
}

func TestGoArgReproduceProblemSimpler(t *testing.T) {
	envConfig := TestConfig{}
	os.Setenv("ELBOW_FILE_AGE", "3")
	arg.MustParse(&envConfig)
}
```

Error from failed test:

```
$ go test -v
=== RUN   TestGoArgReproduceProblemSimpler
Usage: goarg-issue97.test.exe [--age AGE] [--keep-old]
error: unknown argument -test.timeout=10m0s
exit status 4294967295
FAIL    github.com/atc0005/goarg-issue97        0.261s
```

```ShellSession
$ cat go.mod
module github.com/atc0005/goarg-issue97

go 1.13

require github.com/alexflint/go-arg v1.2.0
```

I haven't published the code via a Git repo, but can do that if it would be helpful.

**Comment by atc0005** [comment]
I found this:

> It is sometimes necessary for a test program to do extra setup or teardown before or after testing. It is also sometimes necessary for a test to control which code runs on the main thread. To support these and other cases, if a test file contains a function:
> 
> ```golang
> func TestMain(m *testing.M)
> ```
> 
> then the generated test will call TestMain(m) instead of running the tests directly. TestMain runs in the main goroutine and can do whatever setup and teardown is necessary around a call to m.Run. It should then call os.Exit with the result of m.Run. When TestMain is called, flag.Parse has not been run. If TestMain depends on command-line flags, including those of the testing package, it should call flag.Parse explicitly.
> 
> A simple implementation of TestMain is:
> 
> ```golang
> func TestMain(m *testing.M) {
> 	// call flag.Parse() here if TestMain uses flags
> 	os.Exit(m.Run())
> }
> ```

Is the fix to run my test code within a `TestMain()` function?

refs: https://golang.org/pkg/testing/#hdr-Main

**Comment by atc0005** [comment]
> Is the fix to run my test code within a `TestMain()` function?
> 
> refs: https://golang.org/pkg/testing/#hdr-Main

I didn't have any luck with that approach, but maybe it's still me doing something wrong.

**Comment by alexflint** [comment]
Try adding the following line at the top of your test:
```
os.Args = nil
```
So the full working example is:
```
package main

import (
	"os"
	"testing"

	"github.com/alexflint/go-arg"
)

type TestConfig struct {
	Option1 int  `arg:"--age,env:TESTING_OPTION1" help:"Placeholder for option 1"`
	Option2 bool `arg:"--keep-old,env:TESTING_OPTION2" help:"Placeholder for option 2"`
}

func TestGoArgReproduceProblemSimpler(t *testing.T) {
	os.Args = nil
	envConfig := TestConfig{}
	os.Setenv("ELBOW_FILE_AGE", "3")
	arg.MustParse(&envConfig)
}
```

**Comment by atc0005** [comment]
lol, I am so embarrassed. I considered modifying os.Args to remove just the one offending flag, but assumed that it wasn't a reliable option long-term (e.g., what if the next Go release adds a new flag that is passed by default by the testing package?), but failed to catch that by the time my test modifies os.Args that the testing package has already done what it needs with the os.Args slice.

Thanks for pointing this out. Will give this a try and respond back.

Thank you for your help!

**Comment by atc0005** [comment]
That worked perfectly, thanks!

**Comment by sabuhish** [comment]
I am encountering the same issue while running tests for endpoints that I wrote in gin. 

`os.Args = nil` Does not solve while running tests for gin, unfortunately. 

The issue  I get:

```error: unknown argument -test.testlogfile=/tmp/go-build2608185524/b196/testlog.txt```

**Comment by alexflint** [comment]
@sabuhish The reason for this is that "go test" adds command line arguments when it invokes each test. This then causes go-arg to complain because it doesn't know what to do with them. The way to avoid this is either to modify `os.Args`, or (best option) pass command line arguments as a list of strings from your test and avoid using `os.Args` at all. To do this second option you will need to create a parser with `p, err := arg.NewParser` and then pass a list of strings to it via `p.Parse(myArgs)`.

If your test is simple and self-contained then feel free to post it here and I can show you how to modify it.

**Comment by sabuhish** [comment]
@alexflint Thank you for the solution, Indeed it helped me a lot. I went through the source code, in order to better debug it.

Well, let me share a snippet that might be useful for others as well, in case. I split command line arguments into two part, one for test cases one for development.

cheking whatver it is test case or not `Testing = strings.HasSuffix(os.Args[0], ".test")`
Then as you suggested to use `arg.NewParser`:
```
if Testing {
		p, _ := arg.NewParser(arg.Config{Program: "test"}, &Config)
		settings := []string{"--settings=test"}
		p.Parse(settings)
} else {
		arg.MustParse(&Config)

	}
```
Thanks again!

**Comment by imarsman** [comment]
Well, I must say it is great to have a solution to this. Thank-you very much.

**Comment by guluguru** [comment]
I'm working on API test and encounter such error too: 
- unknown argument -test.paniconexit0, 
- unknown argument -test.run, etc

The reason why I comment here is for SEO, as it took me a lot of effort to find that issue.

Replies above has already explained the reasons and solutions well, but if someone is not familiar with that repo, perhaps more examples or context would be helpful: 

before, which not works
```go
var args cliArgs
arg.MustParse(&args)
```

after, which works
```go
if os.Getenv("TEST") == "1" {
    InTest = true
}

var args cliArgs
if InTest { // os.Args here would be []string{"xxxxx__debug", "-test.run", "^TestXXX$"}, and go-args count not  handle it well
    p, err := arg.NewParser(arg.Config{Program: "blog"}, &args)
    if err != nil {
        panic(err)
    }
    settings := []string{"-m", "cli", "-c", ".env"}
    p.Parse(settings)
} else {
    arg.MustParse(&args)
}
```

Of course, you need to set Environment to told program that it is InTest:

`TEST=1 go test -v`

or if you are tesing with VSCode, in .vscode/settings.json:

```json
{
    "go.testEnvVars": {
        "TEST": "1"
    }
}
```
