### ISSUE TITLE
Option Group Default or Is It a Default

### ISSUE THREAD

**Issue by runeimp** [alexflint/go-arg#99]
This may already be possible and I'm just overlooking somehow but I was wondering if option groups are part of the spec. What I'm specifically looking for is to make certain options part of a group and be able to check if anything in the group was set at all. This would facilitate the ability to define a default for an option that is only active when nothing in the group was set. If that's not a thing is there a way to check if a variable was actually set and not just defaulted? That would also provide the functionality I'm looking for.

**Comment by atc0005** [comment]
@runeimp check out #94 re determining whether an option was set. Using pointers worked for my use case.

**Comment by runeimp** [comment]
@atc0005 that is a great discussion. That definitely helps. I'm not a big fan of all the changes I need to make to handle nil pointers but it's functional. The group thing would save a lot of code for this one use case but I've already written most of the code needed and I don't think I've ever really needed that feature before. But I also know exactly why that feature exists in some other libraries I've seen now.  😉

**Comment by runeimp** [comment]
Leaving this open for a bit. I'd love to hear any thoughts the author or anyone else may have before closing it.

**Comment by dallbee** [comment]
@runeimp You might also consider using `parser.Subcommand`: https://godoc.org/github.com/alexflint/go-arg#Parser.Subcommand

The way I structure cli applications with go-arg is along the lines of:

```.go
type runner interface {
    func Run(p Printer) error
}

type Cmd struct {
    Sub *SubCmd
}

func (cmd *Cmd) Run(p Printer) error {
    p.Print("running")
    return nil
}

type SubCmd struct {}

func (cmd *SubCmd) Run(p Printer) error {
    p.Print("sub command running")
    return nil
}

func main() {
    args := Cmd {
        // set defaults
    }

    printer := log.New(os.Stdout, "", 0)
    p := arg.MustParse(&args)
    if err := p.Subcommand().(runner).Run(printer); err != nil {
        log.Fatal(err)
    }
}
```

**Comment by runeimp** [comment]
@dallbee that's interesting. Is the casting to `runner` necessary though?

**Comment by dallbee** [comment]
The type assertion (not a cast) is needed in that example because `p.Subcommand()` is an empty interface type.

**Comment by alexflint** [comment]
Hi @runeimp. Apologies for the long delay in responding.

From what I understand you're asking whether there is a way to determine whether any one of a set of options was provided by the user. Is that correct?

One way to do that at the moment is like this:

```
var args struct {
  A *string
  B *string
  C *string
}
p := args.MustParse(&args)
if args.A == nil && args.B == nil && args.C == nil {
  p.Fail("you must provide either --a or --b or --c")
}
```

However, this doesn't work if you use the `default` tag. **If you do use defaults, there is currently no way to determine whether an option value was provided by the user, or came from a default value**. This is a shortcoming of the library - apologies for this.

One workaround is to not use the `default` tag and instead insert the default values yourself:

```
var args struct {
  A *string
  B *string
  C *string
}
p := args.MustParse(&args)

// first check that one of --a or --b or --c was provided explicitly by the user 
if args.A == nil && args.B == nil && args.C == nil {
  p.Fail("you must provide either --a or --b or --c")
}

// next apply default values
if args.A == nil {
  args.A = new(string)
  *args.A := "default value for A"
}
if args.B == nil {
  args.B = new(string)
  *args.B := "default value for A"
}
if args.C == nil {
  args.C = new(string)
  *args.C := "default value for A"
}
```
I realize this is a little cumbersome. If you can think of an elegant way to expose whether a value came from a default or from the user via the command line, I'd be open to incorporating that into the library.

Thanks for this discussion all.

**Comment by runeimp** [comment]
Hey @alexflint, thanks for the response. I believe I used a method inspired by @dallbee's comment to help manage the situation. I can't remember which project it was at the moment to verify but I believe that's what I did. 😁
